### ISSUE TITLE
`example-lua-vfs` should use CMakeLists.txt for spiffs creation.

### ISSUE THREAD

**Issue by KT819GM** [UncleRus/esp-idf-lua#1]
Adding
```C
spiffs_create_partition_image(storage spiffs_image FLASH_IN_PROJECT)
```
into `CMakeLists.txt` will allow to fully flash mcu trough VSCode official Espressif plugin using ESP-IDF 4.x (cmake, ninja).

Thank you for this component.

**Comment by UncleRus** [comment]
Could you create a pull request?
