### ISSUE TITLE
main.c:70:34: error: format '%d' expects argument of type 'int', but argument 2 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]    70 |     printf("State closed, heap: %d\n", xPortGetFreeHeapSize());

### ISSUE THREAD

**Issue by franz-ms-muc** [UncleRus/esp-idf-lua#6]
main.c:70:34: error: format '%d' expects argument of type 'int', but argument 2 has type 'uint32\_t' {aka 'long unsigned int'} \[-Werror=format=\]

70 | printf("State closed, heap: %d\\n", xPortGetFreeHeapSize());

**Comment by franz-ms-muc** [comment]
[https://github.com/espressif/esp-idf/blob/master/examples/get-started/hello_world/main/hello_world_main.c](https://github.com/espressif/esp-idf/blob/master/examples/get-started/hello_world/main/hello_world_main.c)

this File show how to avoid it.

**Comment by whc2001** [comment]
With this on IDF 5.1.4 I am getting:
```
error: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
   31 |     printf("Start, heap: %" PRIu32 "\n", xPortGetFreeHeapSize());
      |            ^~~~~~~~~~~~~~~~              ~~~~~~~~~~~~~~~~~~~~~~
      |                                          |
      |                                          size_t {aka unsigned int}
```

Changing `%" PRIu32 "` to `%zu` works for me
